index_page:
    pattern:  /
    defaults: { _controller: "WizardryMainBundle:Default:index" }


app_set_show:
    pattern:  /set/{id}
    defaults: { _controller: "WizardryMainBundle:Set:show" }

app_card_show:
    pattern:  /card/{id}
    defaults: { _controller: "WizardryMainBundle:Card:show" }

